import { GeistSans } from 'geist/font/sans';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-full min-h-screen">
      <body className={`bg-[#bbbcb0] dark:bg-black ${GeistSans.className}`}>{children}</body>
    </html>
  );
}
